package main

import (
	"bytes"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

const fixtureSpec = `openapi: 3.0.1
info:
  title: Fixture API
  version: v9
servers:
  - url: https://api-dev.example.com
paths:
  /things/{id}/actions/run:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    post:
      summary: Run a thing
      operationId: runThing
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Thing"
      responses:
        "202":
          $ref: "#/components/responses/Accepted"
  /things:
    get:
      summary: List things
      operationId: listThings
      responses:
        "200":
          description: OK
components:
  schemas:
    Thing:
      type: object
      properties:
        nested:
          $ref: "#/components/schemas/Nested"
    Nested:
      type: string
    Unrelated:
      type: object
  responses:
    Accepted:
      description: Accepted
`

var fixtureManifest = manifest{
	Source: "fixture",
	Operations: []manifestOperation{
		{OperationID: "runThing", CLIName: "run-thing", EarlyAccess: "CMP-1"},
	},
}

func TestGenerateExtractsOperationAndClosure(t *testing.T) {
	output, err := generate([]byte(fixtureSpec), fixtureManifest, "fixture")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	text := string(output)

	for _, want := range []string{
		"/things/{id}/actions/run:",
		"x-cli-name: run-thing",
		"x-dci-early-access: CMP-1",
		"Thing:",
		"Nested:",
		"Accepted:",
		"url: /",
		"# Code generated by tools/betaspec",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("output missing %q", want)
		}
	}
	for _, unwanted := range []string{
		"listThings",
		"Unrelated:",
		"api-dev.example.com",
	} {
		if strings.Contains(text, unwanted) {
			t.Errorf("output should not contain %q", unwanted)
		}
	}

	// Path-level parameters ride along with the kept method.
	var document struct {
		Paths map[string]map[string]any `yaml:"paths"`
	}
	if err := yaml.Unmarshal(output, &document); err != nil {
		t.Fatalf("output does not parse: %v", err)
	}
	item := document.Paths["/things/{id}/actions/run"]
	if item["parameters"] == nil {
		t.Error("path-level parameters were dropped")
	}
	if item["post"] == nil {
		t.Error("kept method missing")
	}
}

func TestGenerateIsDeterministic(t *testing.T) {
	first, err := generate([]byte(fixtureSpec), fixtureManifest, "fixture")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	second, err := generate([]byte(fixtureSpec), fixtureManifest, "fixture")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Error("output is not deterministic")
	}
}

func TestGenerateReportsMissingOperations(t *testing.T) {
	m := manifest{Operations: []manifestOperation{
		{OperationID: "doesNotExist", CLIName: "nope"},
	}}
	_, err := generate([]byte(fixtureSpec), m, "fixture")
	if err == nil || !strings.Contains(err.Error(), "doesNotExist") {
		t.Fatalf("expected missing-operation error, got %v", err)
	}
}

func TestGenerateRejectsExternalRefs(t *testing.T) {
	spec := strings.Replace(fixtureSpec, `"#/components/schemas/Thing"`, `"./other.yaml#/Thing"`, 1)
	_, err := generate([]byte(spec), fixtureManifest, "fixture")
	if err == nil || !strings.Contains(err.Error(), "unsupported $ref") {
		t.Fatalf("expected unsupported-$ref error, got %v", err)
	}
}
