documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum

go:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"
