name: Assign PR Author

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: toshimaru/auto-author-assign@5cd66f093de6691e0812ef186b7492589b0b7866
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
